2025-01-03 15:50:21,583: asyncio: INFO: [MLTrader] Executing the initialize lifecycle method
2025-01-03 15:50:22,027: root: INFO: Current backtesting datetime 2023-12-01 08:30:00-05:00
2025-01-03 15:50:22,027: asyncio: INFO: [MLTrader] Executing the before_market_opens lifecycle method
2025-01-03 15:50:22,028: root: INFO: Current backtesting datetime 2023-12-01 09:30:00-05:00
2025-01-03 15:50:22,028: asyncio: INFO: [MLTrader] Executing the before_starting_trading lifecycle method
2025-01-03 15:50:22,028: asyncio: INFO: [MLTrader] [34mExecuting the on_trading_iteration lifecycle method at 2025-01-03 15:50:22[0m
2025-01-03 15:50:22,028: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2025-01-03 15:50:23,123: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2025-01-03 15:50:30,107: httpx: INFO: HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
2025-01-03 15:50:31,024: asyncio: INFO: [MLTrader] [32mNew order was created: market order of | 1.0 BTCUSD buy | at price $46427.1328125 of class bracket with status new[0m
2025-01-03 15:50:31,029: asyncio: INFO: [MLTrader] [34mTrading iteration ended at 2025-01-03 15:50:31[0m
2025-01-03 15:50:31,029: asyncio: INFO: [MLTrader] Getting historical prices for BTCUSD, 1 bars, 
2025-01-03 15:50:31,030: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2025-01-03 15:50:33,381: yfinance: ERROR: $BTCUSD: possibly delisted; No timezone found
2025-01-03 15:50:35,293: yfinance: ERROR: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/BTCUSD?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=BTCUSD&crumb=e4kC5QBip3G
2025-01-03 15:50:35,410: root: ERROR: YAHOO did not return data for symbol BTCUSD. Make sure this symbol is valid.
2025-01-03 15:50:35,410: asyncio: ERROR: [MLTrader] 'NoneType' object has no attribute 'df'
2025-01-03 15:50:35,413: asyncio: ERROR: [MLTrader] Traceback (most recent call last):
  File "/opt/anaconda3/envs/devin/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 923, in run
    self._run_trading_session()
  File "/opt/anaconda3/envs/devin/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 874, in _run_trading_session
    self.broker.process_pending_orders(strategy=self.strategy)
  File "/opt/anaconda3/envs/devin/lib/python3.11/site-packages/lumibot/backtesting/backtesting_broker.py", line 574, in process_pending_orders
    dt = ohlc.df.index[-1]
         ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'df'

2025-01-03 15:50:35,413: asyncio: INFO: [MLTrader] Executing the on_bot_crash event method
2025-01-03 15:50:37,283: root: INFO: Backtesting finished
2025-01-03 15:50:38,752: root: ERROR: Not enough data to create a tearsheet, at least 2 days of data are required. Skipping
2025-01-03 15:50:38,752: backtest_stats: INFO: Backtest took 0:00:17.169853 for a speed of 0.000
